/*
 Navicat Premium Data Transfer

 Source Server         : localmicrosd
 Source Server Type    : MySQL
 Source Server Version : 100138
 Source Host           : localhost:3306
 Source Schema         : supreme_user3

 Target Server Type    : MySQL
 Target Server Version : 100138
 File Encoding         : 65001

 Date: 07/09/2019 14:11:12
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for cmms_email_notification_setting
-- ----------------------------
DROP TABLE IF EXISTS `cmms_email_notification_setting`;
CREATE TABLE `cmms_email_notification_setting`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` int(11) NOT NULL,
  `TITLE` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `OPEN_VALUE` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `CLOSE_VALUE` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `CATEGORY` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `GRUB_MENU` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `ROLES` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `CREATE_BY` int(11) NOT NULL,
  `CREATE_DATE` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `UPDATE_BY` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `UPDATE_DATE` datetime(0) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(0),
  `IS_DEL` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `TITLE`(`TITLE`, `CATEGORY_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of cmms_email_notification_setting
-- ----------------------------
INSERT INTO `cmms_email_notification_setting` VALUES (1, 0, 'Notification for Work Request Approval', '<p>Greetings,</p>\r\n\r\n<p>Please review and approve below Work Request.</p>\r\n\r\n<p>Work Request Number : __wrno__<br />\r\nRequestor : __createdby__<br />\r\nRequested Time : __createdat__<br />\r\nPriority : __wrpriority__</p>', '<p>Thank you,<br />\r\nSupreme Energy - CMMS Portal</p>\r\n\r\n<p>Note: This email is generated by system, do not reply.</p>\r\n', 'wr_supervisor_approval', NULL, NULL, 0, '2019-09-07 13:45:52', NULL, '2019-09-07 13:55:01', 0);

SET FOREIGN_KEY_CHECKS = 1;
